config/routes.rb
Rails.application.routes.draw do

 root 'welcome#index'
 
 post 'import', to: 'welcome#import'
 get  'import', to: 'welcome#index'
 

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base



end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end
  
  def import
     @raw_Data=CSV.read(params[:file].path, :col_sep => "," ,:headers => true, :row_sep => :auto,  :encoding  =>'iso-8859-1:utf-8')
     ##CSV.read(params[:file].path, headers: true, encoding:'iso-8859-1:utf-8')
     

     flash[:notice]= "File Imported Succefully"
     render 'import'
     

  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Synergy Field Audit</title>
  <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name,msg| %>
	<div class='alert alert-<%="#{name}" %>'>
		<a href="#" class="close" data-dismiss="alert">×</a>	
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	</div>
	<% end %>


<%= yield %>

<hr/>
<footer>
	Synergy @2017
</footer>

</body>
</html>

app/views/welcome/import.html.erb
<center><h2>Audit Report</h2></center>	

<% if @raw_Data %>
<% data = [] %>

<div class="container">
	<div class="row">
		<div class='col-xs-12'>
			<div class="col-xs-3 myheader error1"> Interview Started before 8.00 am </div>
			<div class="col-xs-3 myheader error2"> Interview Started after 11.30 pm </div>
			<div class="col-xs-3 myheader error3"> Duplicate Telephone Number </div>
		</div>	
	</div>	
	
	<hr/>
	
	
<div class="row">
	<div class='col-xs-12'>
 <% data=@raw_Data['TelNo']  %>
 
	<% @raw_Data.headers.each  do |myheader|%>
		<div class="col-xs-2 myheader"> <%=myheader%> </div>
	<% end %>	
	<div class="col-xs-2 myheader"> LOI (in mins) </div>
</div>	
</div>


	<% @raw_Data.each do |id|%>

     <%error_1=0%>
     <%error_2=0%>
     <%error_3=0%>		
		<%id[4]=TimeDifference.between(id[2], id[1]).in_minutes%>
		
		
		
		<% if (DateTime.parse(id[1]).to_s(:time) < "08:00") %>
			<% error_1=1  %>
		<% end %>

		<% if (DateTime.parse(id[1]).to_s(:time) > "23:30") %>
			<% error_2=2  %>
		<% end %>


		<% if data.count(id[3])>1 %>
			  <% error_3=3  %>
		<% end %>
		
		<% error=1000+(100*error_1)+(10*error_2)+error_3%>
		
		<% if error>1000%>
				<div class="row">
					<div class='col-xs-12'>
							<div class="col-xs-2 mytext"> <%=id[0]%> </div>
							
							<% if error_1==1 %>
										<div class="col-xs-2 mytext error1">
							<% else %>	<div class="col-xs-2 mytext"> 
							<% end %>	
							<%=id[1]%> </div>
							
							<% if error_2==2 %>
										<div class="col-xs-2 mytext error2">
							<% else %>	<div class="col-xs-2 mytext"> 
							<% end %>	
							<%=id[2]%> </div>
							
							
							<% if error_3==3 %>
										<div class="col-xs-2 mytext error3">
							<% else %>	<div class="col-xs-2 mytext"> 
							<% end %>	
							<%=id[3] %> </div>
							
							<div class="col-xs-2 mytext"> <%=id[4]%> </div>
					</div>
				</div>
		<% end %>
		
		
	<% end %>
	
</table>	
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="container">
<center><h2>Audit Module</h2></center>	
<%= form_tag(import_path, method: :post, class: 'form-horizontal',multipart: true)  do %>
  <div class="form-group">
  <%= file_field_tag :file,class: 'form-control' %>
  </div>
  <div class="form-group">
  	<%= submit_tag("Import",class: "btn btn-primary btn-lg btn-center") %>
  </div>
<% end %>

<hr/>
	<ul>
		<li> Input CSV File Format</li>
			<ul>
				<ol>Field 1 ==>Id</ol>
				<ol>Field 2 ==>Start Time</ol>
				<ol>Field 3 ==>End time</ol>
				<ol>Field 4 ==>Telephone</ol>	
			</ul>
		<li> Check Record which started before 8 am </li>	
		<li> Check Record which started After 11.30 am </li>
		<li> Check Record which started Duplicate 8 am </li>
	</ul>


</div>